import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Header from "../components/header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Moultrie Animal Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} min-h-screen`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
