name: Build

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_ENVIRONMENT_ID }}
  CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN }}
  CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}
  NEXT_PUBLIC_FORMSPREE_NEW_CLIENT_REGISTRATION_FORM: ${{ secrets.NEXT_PUBLIC_FORMSPREE_NEW_CLIENT_REGISTRATION_FORM }}

on:
  # Run the build for pushes and pull requests targeting main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup Node
      - name: Setup (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # Install
      - name: Install
        run: npm ci --legacy-peer-deps
      # Checks
      - name: Lint
        run: npm run lint
      # Test
      - name: Test
        run: npm run test
      # Build
      - name: Build
        run: npm run build
